Repository submariner-io/submariner-charts, pull requests merged in 2021-05, with the labels that each got.

#139 Don't run certain GHA jobs on forks
  .github/workflows/flake_finder.yml
  .github/workflows/periodic.yml
  .github/workflows/release.yml
Labels: automation

#142 Add CII and merged-CI badges to README
  README.md
Labels: cncf, docs

#141 fix(rbac): add missing cluster roles to submariner-operator
  submariner-operator/templates/rbac.yaml
Labels: ready-to-test
