Repository submariner-io/submariner-charts, pull requests merged in 2022-10, with the labels that each got.

#278 Automated backport of #268: Use the default kind CNI
  .shipyard.e2e.yml
Labels: ready-to-test, automated-backport

#279 Automated backport of #268: Use the default kind CNI
  .shipyard.e2e.yml
Labels: ready-to-test, automated-backport

#284 Add issues:write permission to broken links GHA
  .github/workflows/periodic.yml
Labels: automation, ready-to-test

#286 Remove hard-coded latest version from the chart READMEs
  submariner-k8s-broker/README.md
  submariner-operator/README.md
Labels: ready-to-test
