Repository submariner-io/submariner-charts, pull requests merged in 2022-05, with the labels that each got.

#210 Add Dependabot updates of GitHub Actions
  .github/dependabot.yml
Labels: ready-to-test, maintenance

#218 Bump markdown-link-check to the current tip
  .github/workflows/linting.yml
  .github/workflows/periodic.yml
Labels: ready-to-test, maintenance

#220 Use Dependabot to update GHAs on release-0.12
  .github/dependabot.yml
Labels: ready-to-test, maintenance

#229 Automated backport of #218: Bump markdown-link-check to the current tip
  .github/workflows/linting.yml
  .github/workflows/periodic.yml
Labels: automated-backport

#230 Mark the source directory as safe
  Dockerfile.dapper
Labels: ready-to-test
