Repository submariner-io/submariner-charts, pull requests merged in 2022-01, with the labels that each got.

#194 Globalnet include ClusterRole for services
  submariner-operator/templates/rbac.yaml
Labels: ready-to-test

#193 Fix coreDNSCustomConfig values
  submariner-operator/templates/submariner.yaml
Labels: ready-to-test

#196 Configure RBAC for Globalnet pods on OCP deployments
  submariner-operator/templates/rbac.yaml
Labels: ready-to-test

#197 Update K8s in E2E, EOL 1.19 and add 1.23
  .github/workflows/e2e-full.yml
Labels: automation, ready-to-test

#198 Check for fixup commits in PRs
  .github/workflows/linting.yml
Labels: ready-to-test

#200 Bump to 0.11.1
  Makefile
  submariner-operator/Chart.yaml
  submariner-operator/README.md
  submariner-operator/questions.yml
  submariner-operator/values.yaml
Labels: ready-to-test, dependent
