Repository submariner-io/submariner-charts, pull requests merged in 2023-11, with the labels that each got.

#451 Add lease RBAC perm to submariner-globalnet role
  submariner-operator/templates/rbac.yaml
Labels: ready-to-test

#452 Automated backport of #451: Add lease RBAC perm to submariner-globalnet role
  submariner-operator/templates/rbac.yaml
Labels: ready-to-test, release-note-needed, automated-backport

#455 Switch from stale app to stale GHA
  .github/stale.yml
  .github/workflows/stale.yml
Labels: automation, ready-to-test
